project_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST_DEV') }}" # e.g., localhost or your database IP
      port: 5432                                   # Default PostgreSQL port
      user: "{{ env_var('DBT_POSTGRES_USER_DEV') }}" # Your PostgreSQL username
      password: "{{ env_var('DBT_POSTGRES_PASSWORD_DEV') }}" # Your PostgreSQL password
      dbname: "{{ env_var('DBT_POSTGRES_DB_DEV') }}"  # The name of your database
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA_DEV') }}" # Schema to target
      threads: 4                                   # Number of threads for dbt to use
      keepalives_idle: 0                           # Optional: keep connection alive
    prod:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST_PROD') }}"
      port: 5432
      user: "{{ env_var('DBT_POSTGRES_USER_PROD') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD_PROD') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB_PROD') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA_PROD') }}"
      threads: 4
      keepalives_idle: 0
