# movies/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MovieInfoViewSet, get_top_10_movies_view, get_top_movies_paginated_view

router = DefaultRouter()
router.register(r'', MovieInfoViewSet)

urlpatterns = [
    path("top-movies/", get_top_10_movies_view, name="top-movies"),
    path("top-movies-paginated/", get_top_movies_paginated_view, name="top-movies-paginated"),
    path('', include(router.urls)),  # Automatically add the routes generated by the router
]
