# Generated by Django 5.1.4 on 2025-02-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "app"."user_movie" DROP CONSTRAINT IF EXISTS "user_movie_movie_id_aa0e309b_fk_movie_id";
            ALTER TABLE "app"."user_movie" DROP CONSTRAINT IF EXISTS "user_movie_user_id_movie_id_9c60dcb6_uniq";
            ALTER TABLE "app"."user_movie"
            ADD CONSTRAINT "user_movie_movie_id_fk_new" FOREIGN KEY (movie_id)
            REFERENCES "dw_movies"."dim_movie_info" (movie_id)
            DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            -- Optionally provide reverse SQL here.
            """
        ),
    ]
